server:
  port: 0 #项目端口

debug: false

spring:
  datasource:
    url: jdbc:mysql://10.10.10.111:4306/xsun_group?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: xsun_group
    password: kqh9845lddGFdb5E
    filters: log4j,wall,mergeStat
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver


#        name: hantek
#        url: jdbc:oracle:thin:@10.1.4.126:1521:orcl
#        username: hantek
#        password: password
#        filters: stat
#        maxActive: 20
#        initialSize: 1
#        maxWait: 60000
#        minIdle: 1
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: select 'x'
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxOpenPreparedStatements: 20

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:com/dz/generator/mapper/xml/*.xml
  typeAliasesPackage: com.dz.generator.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用